# BigFrames API Coverage Report

This notebook estimates BigFrame's coverage of Pandas APIs by:

1. Extracting the members from pandas, pandas.DataFrame, pandas.Index, pandas.Series
2. Checking if they are present in BigFrames
3. Searching them all on a dataset of 170k unique ipython notebooks queried from GitHub

TODO(bmil): add estimates based on Kaggle notebooks

In [1]:
import pandas as pd
import bigframes as bf
import inspect

token_map = {}
targets = [("pandas", pd, bf), ("dataframe", pd.DataFrame, bf.DataFrame), ("series", pd.Series, bf.Series), ("index", pd.Index, None)]
indexers = ['loc', 'iloc', 'iat', 'ix', 'at']
for name, pandas_obj, bigframes_obj in targets:
    for member in dir(pandas_obj):
        # skip private functions and properties
        if member[0] == "_" and member[1] != "_":
            continue

        if inspect.isfunction(getattr(pandas_obj, member)):
            # Function, match .member(
            token = f"\\.{member}\\("
            token_type = "function"
        elif member in indexers:
            # Indexer, match .indexer[
            token = f"\\.{member}\\["
            token_type = "indexer"
        else:
            # Property
            token = f"\\.{member}\\b"
            token_type = "property"

        is_in_bigframes = hasattr(bigframes_obj, member)

        # Special case: bigframes also implements some top level APIs on 'session'
        if name == "pandas":
            is_in_bigframes = is_in_bigframes or hasattr(bf.Session, member)

        if token not in token_map:
            token_map[token] = ([], token_type, is_in_bigframes)

        token_map[token][0].append(name)

header = ['pattern', 'token_type', 'is_pandas', 'is_dataframe', 'is_series', 'is_index', 'is_in_bigframes']
rows = [[
        k, v[1], 'pandas' in v[0], 'dataframe' in v[0], 'series' in v[0], 'index' in v[0], v[2]
                ] for k, v in token_map.items()]

# Wishlist: constructors for BigFrames...
pandas_df = pd.DataFrame(rows, columns=header)
pandas_df

/tmp/ipykernel_3446083/3523007326.py:14: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  if inspect.isfunction(getattr(pandas_obj, member)):
/tmp/ipykernel_3446083/3523007326.py:14: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  if inspect.isfunction(getattr(pandas_obj, member)):
/tmp/ipykernel_3446083/3523007326.py:14: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  if inspect.isfunction(getattr(pandas_obj, member)):

,pattern,token_type,is_pandas,is_dataframe,is_series,is_index,is_in_bigframes
0,\.ArrowDtype\b,property,True,False,False,False,False
1,\.BooleanDtype\b,property,True,False,False,False,False
2,\.Categorical\b,property,True,False,False,False,False
3,\.CategoricalDtype\b,property,True,False,False,False,False
4,\.CategoricalIndex\b,property,True,False,False,False,False
...,...,...,...,...,...,...,...
495,\.symmetric_difference\(,function,False,False,False,True,False
496,\.to_flat_index\(,function,False,False,False,True,False
497,\.to_native_types\(,function,False,False,False,True,False
498,\.to_series\(,function,False,False,False,True,False
499,\.union\(,function,False,False,False,True,False

This query will count the occurrence of the API patterns in a dump of 170,000 deduped IPython notebooks taken from the public GitHub dataset.

In [2]:
session = bf.connect()
df = session.read_pandas(pandas_df)

# Soon, we could do all this in BigFrames...... ðŸ¤ž
# TODO: see how much we can rewrite
sql = f"""
WITH
  token_patterns AS ( {df.sql} ),
  kaggle_hit_counts AS (
    SELECT pattern, private_matches, public_matches, private_scanned, public_scanned
    FROM `bigframes-dev.coverage_report.kaggle_pandas_hit_counts`),
  github_notebooks AS (SELECT content FROM `bigframes-dev.coverage_report.github_notebooks`),
  github_hit_counts AS (
    SELECT
      token_patterns.pattern,
      COUNTIF(REGEXP_CONTAINS(github_notebooks.content, token_patterns.pattern)) AS matches,
      COUNT(*) AS scanned
    FROM
      token_patterns, github_notebooks
    WHERE CONTAINS_SUBSTR(github_notebooks.content, 'import pandas')
    GROUP BY token_patterns.pattern
    ORDER BY matches DESC
)
SELECT
  token_patterns.*,
  github_hit_counts.matches AS github_matches,
  github_hit_counts.scanned AS github_scanned,
  kaggle_hit_counts.private_matches AS kaggle_priv_matches,
  kaggle_hit_counts.private_scanned AS kaggle_priv_scanned,
  kaggle_hit_counts.public_matches AS kaggle_pub_matches,
  kaggle_hit_counts.public_scanned AS kaggle_pub_scanned
FROM token_patterns
LEFT JOIN kaggle_hit_counts ON token_patterns.pattern = kaggle_hit_counts.pattern
LEFT JOIN github_hit_counts ON token_patterns.pattern = github_hit_counts.pattern
"""

df = session.read_gbq(sql)

df

                pattern token_type  is_pandas  is_dataframe  is_series  \
0        \.ArrowDtype\b   property       True         False      False
1      \.BooleanDtype\b   property       True         False      False
2       \.Categorical\b   property       True         False      False
3  \.CategoricalDtype\b   property       True         False      False
4  \.CategoricalIndex\b   property       True         False      False
5        \.DateOffset\b   property       True         False      False
6     \.DatetimeIndex\b   property       True         False      False
7   \.DatetimeTZDtype\b   property       True         False      False
8         \.ExcelFile\b   property       True         False      False
9       \.ExcelWriter\b   property       True         False      False

   is_index  is_in_bigframes  github_matches  github_scanned  \
0     False            False               0           40337
1     False            False               1           40337
2     False            False             233           40337
3     False            False              25           40337
4     False            False               3           40337
5     False            False              75           40337
6     False            False             491           40337
7     False            False               4           40337
8     False            False             123           40337
9     False            False             164           40337

   kaggle_priv_matches  kaggle_priv_scanned  kaggle_pub_matches  \
0                 <NA>                 <NA>                <NA>
1                   51             20398148                   0
2                67152             20398148               17157
3                18254             20398148                1882
4                 1903             20398148                 255
5                16205             20398148                2752
6                64117             20398148               17657
7                 3592             20398148                 339
8                 8527             20398148                1001
9                10968             20398148                1174

   kaggle_pub_scanned
0                <NA>
1             3429346
2             3429346
3             3429346
4             3429346
5             3429346
6             3429346
7             3429346
8             3429346
9             3429346
...

[500 rows x 13 columns]

In [3]:
# TODO: rewrite everything in bigframes. Too much missing right now :(
df = df.to_pandas()
df

,pattern,token_type,is_pandas,is_dataframe,is_series,is_index,is_in_bigframes,github_matches,github_scanned,kaggle_priv_matches,kaggle_priv_scanned,kaggle_pub_matches,kaggle_pub_scanned
0,\.ArrowDtype\b,property,True,False,False,False,False,0,40337,<NA>,<NA>,<NA>,<NA>
1,\.BooleanDtype\b,property,True,False,False,False,False,1,40337,51,20398148,0,3429346
2,\.Categorical\b,property,True,False,False,False,False,233,40337,67152,20398148,17157,3429346
3,\.CategoricalDtype\b,property,True,False,False,False,False,25,40337,18254,20398148,1882,3429346
4,\.CategoricalIndex\b,property,True,False,False,False,False,3,40337,1903,20398148,255,3429346
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,\.name\b,property,False,False,True,True,True,3146,40337,1157307,20398148,118453,3429346
496,\.__init__\b,property,False,False,False,True,True,733,40337,3317178,20398148,167504,3429346
497,\.__new__\(,function,False,False,False,True,True,17,40337,2816,20398148,49,3429346
498,\.__reduce__\(,function,False,False,False,True,True,0,40337,16,20398148,1,3429346
499,\.__setattr__\b,property,False,False,False,True,True,8,40337,17646,20398148,427,3429346

In [6]:
df["api"] = df["pattern"].str.replace('[\W(\\\\b)]', '')

# Clean out some properties that are also common python methods
# This is a limitation of the analysis
df = df[~df["api"].isin(["append", "tolist", "format", "items", "keys"])].copy()

/tmp/ipykernel_3446083/301973143.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["api"] = df["pattern"].str.replace('[\W(\\\\b)]', '')

In [7]:
# Weighted total API coverage
matches_stats = df[["github_matches", "kaggle_priv_matches", "kaggle_pub_matches"]]
covered = matches_stats[df["is_in_bigframes"]].sum(axis=0)
total = matches_stats.sum(axis=0)
weighted_percentage = covered * 100 / total
weighted_percentage["average"] = weighted_percentage.mean()
weighted_percentage

github_matches         36.001497
kaggle_priv_matches    37.238972
kaggle_pub_matches     37.199425
average                36.813298
dtype: float64

In [8]:
df["github_pct"] = df["github_matches"] * 100 / df["github_scanned"]
df["kaggle_priv_pct"] = df["kaggle_priv_matches"] * 100 / df["kaggle_priv_scanned"]
df["kaggle_pub_pct"] = df["kaggle_pub_matches"] * 100 / df["kaggle_pub_scanned"]
df["avg_pct"] = (df["github_pct"] + df["kaggle_priv_pct"] + df["kaggle_pub_pct"]) / 3

summary = df[["api", "avg_pct", "github_pct", "kaggle_priv_pct", "kaggle_pub_pct", "is_pandas", "is_dataframe", "is_series", "is_index", "is_in_bigframes"]]
summary = summary.sort_values("avg_pct", ascending=False)

print("The top missing APIs, and the rate at which they appear are:")
summary[summary["is_in_bigframes"] == False].head(50)

The top missing APIs, and the rate at which they appear are:

/tmp/ipykernel_3446083/4131997004.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["github_pct"] = df["github_matches"] * 100 / df["github_scanned"]
/tmp/ipykernel_3446083/4131997004.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["kaggle_priv_pct"] = df["kaggle_priv_matches"] * 100 / df["kaggle_priv_scanned"]
/tmp/ipykernel_3446083/4131997004.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["kaggle_pub_pct"] = df["kaggle_pub_matches"] * 100 / df["kaggle_pub_scanned"]
/tmp/ipykernel_3446083/4131997004.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["avg_pct"] = (df["github_pct"] + df["kaggle_priv_pct"] + df["kaggle_pub_pct"]) / 3

,api,avg_pct,github_pct,kaggle_priv_pct,kaggle_pub_pct,is_pandas,is_dataframe,is_series,is_index,is_in_bigframes
346,values,32.634977,28.254456,36.637184,33.013292,False,True,True,True,False
202,mean,29.681571,26.695094,35.745422,26.604198,False,True,True,False,False
213,plot,29.017144,41.019411,16.955951,29.076069,False,True,True,False,False
245,sum,27.423807,20.370875,32.203629,29.696916,False,True,True,False,False
324,astype,23.895698,15.055656,32.842354,23.789084,False,True,True,True,False
197,loc,23.863418,20.370875,28.866165,22.353213,False,True,True,False,False
351,array,21.421821,22.002132,26.226249,16.037081,False,False,True,True,False
50,array,21.077271,21.607953,25.807519,15.816339,True,False,False,False,False
182,iloc,19.73335,13.597937,22.6275,22.974614,False,True,True,False,False
135,apply,18.815486,15.945658,22.258545,18.242254,False,True,True,False,False
332,groupy,18.810783,16.709225,20.337533,19.385591,False,True,True,True,False
335,max,16.06407,14.244986,20.683035,13.264191,False,True,True,True,False
325,copy,16.048601,11.562585,22.069459,14.513759,False,True,True,True,False
331,fillna,15.48059,8.768624,20.034128,17.639019,False,True,True,True,False
291,value_counts,15.048784,8.587649,12.653708,23.904995,True,True,True,True,False
342,sort_values,14.797895,10.51392,15.619197,18.260566,False,True,True,True,False
290,unique,14.778495,11.299799,17.785169,15.250517,True,False,True,True,False
225,replace,13.037451,11.151052,14.792814,13.168488,False,True,True,False,False
267,transform,12.634484,6.792771,17.408855,13.701825,False,True,True,False,False
160,descrie,12.220551,11.103949,8.438727,17.118978,False,True,True,False,False
287,isnull,11.028831,5.610234,10.472666,17.003592,True,True,True,True,False
337,min,10.964404,11.133699,13.250806,8.508707,False,True,True,True,False
358,map,10.721358,7.335697,14.427707,10.400671,False,False,True,True,False
184,info,10.369795,5.488757,8.650045,16.970583,False,True,True,False,False
69,merge,10.246643,7.405112,14.931292,8.403527,True,True,False,False,False
242,std,9.263207,9.938766,10.628779,7.222077,False,True,True,False,False
178,hist,9.23809,9.990827,5.916351,11.807091,False,True,True,False,False
292,T,9.051587,11.351861,8.45115,7.351752,False,True,True,True,False
152,corr,8.548393,3.431093,5.330807,16.883277,False,True,True,False,False
363,str,8.109375,6.294469,9.439161,8.594496,False,False,True,True,False
65,io,8.006803,12.323673,6.508983,5.187753,True,False,False,False,False
347,where,7.197303,5.06235,10.927821,5.601739,False,True,True,True,False
154,count,7.133105,7.370404,5.866101,8.16281,False,True,True,False,False
348,argmax,7.08252,3.812877,10.712703,6.721981,False,False,True,True,False
176,get,6.841113,9.626398,7.1117,3.785241,False,True,True,False,False
334,isin,6.662762,4.868979,9.417899,5.701408,False,True,True,True,False
61,get_dummies,6.439915,3.178223,7.376292,8.765228,True,False,False,False,False
231,sample,6.286369,4.811959,7.605308,6.441841,False,True,True,False,False
106,to_datetime,6.217714,6.004413,5.345966,7.302763,True,False,False,False,False
59,eval,5.990486,0.937105,13.216773,3.817579,True,True,False,False,False
243,style,5.622405,7.630711,3.153566,6.082938,False,True,False,False,False
203,median,5.590637,3.852542,6.407866,6.511504,False,True,True,False,False
101,set_option,5.534541,4.526861,6.690313,5.38645,True,False,False,False,False
339,nunique,5.425292,0.9495,5.368179,9.958196,False,True,True,True,False
273,update,5.422455,4.573964,8.144239,3.549161,False,True,True,False,False
229,round,5.34716,3.391427,6.864197,5.785855,False,True,True,False,False
248,tail,5.319648,5.939956,4.446409,5.572579,False,True,True,False,False
141,axes,5.033221,13.573146,0.421146,1.105371,False,True,True,False,False
403,sort,4.65722,6.713439,4.83741,2.420811,False,False,False,True,False
345,transpose,4.592386,3.475717,6.866006,3.435436,False,True,True,True,False